#' @title Compute forward vector for HMM 
#' @description Computes the forward vector and loglikelihood for HMM semi parametric model
#' @param hmm - HiddenMarkovModel object
#' @param observation - vector of observations generated by the above class
#' @return forward vector and loglikelihood

setGeneric(name = "computeStartingVector",
           def = function(theObject)
           {
             standardGeneric("computeStartingVector")
           }
)

setMethod(f = "computeStartingVector", 
          signature = "HiddenMarkovModel", 
          definition = function(theObject)
          {
            if(theObject@p > 1 || theObject@p < 0)
            {
              cat("The stationary probability must be between 0 and 1","\n")
              return(theObject)
            }
            p <- theObject@p
            starting_probabilities <- c(p/2, 1-p, p/2)
            return(starting_probabilities)
          }
)

