#' @title Compute forward vector for HMM 
#' @description Computes the forward vector and loglikelihood for HMM semi parametric model
#' @param hmm - HiddenMarkovModel object
#' @param observation - vector of observations generated by the above class
#' @return forward vector and loglikelihood

setGeneric(name = "computeLogLikelihood",
           def = function(theObject, b)
           {
             standardGeneric("computeLogLikelihood")
           }
)

setMethod(f = "computeLogLikelihood", 
          signature = "HiddenMarkovModel", 
          definition = function(theObject, b)
          {
            observations  = getObservationsFromHMM(theObject)
            nObservations  = length(observations)
            transition_matrix <- getTransitionMatrix(theObject)
            starting_probs = computeStartingVector(theObject)
            p <- theObject@p
            theta <- getTheta(theObject)
            allprobs <- computeAllProbabilities(observations,theta, 
                                                p, b)
            lscale <- 0
            # Init
            foo <- starting_probs %*% transition_matrix * allprobs[,1]
            sumfoo <- sum(foo)
            lscale <- lscale + log(sumfoo)
            foo <- foo / sumfoo
            minus_log_likelihood <- -lscale
            
            # Loop over the observations
            for(i in 2:nObservations)
            {
              foo <- foo %*% transition_matrix * allprobs[,i]
              sumfoo <- sum(foo)
              lscale <- log(sumfoo)
              foo <- foo / sumfoo
              minus_log_likelihood[i] <- -lscale
            }
            return(list(
              minus_log_like_vector = minus_log_likelihood,
              mllk = tail(minus_log_likelihood,n = 1)
            ))
          }
)

