#' @title Compute forward vector for HMM 
#' @description Computes the forward vector and loglikelihood for HMM semi parametric model
#' @param hmm - HiddenMarkovModel object
#' @param observation - vector of observations generated by the above class
#' @return forward vector and loglikelihood

setGeneric(name = "computeBackwardVector",
           def = function(hmm_object)
           {
             standardGeneric("computeBackwardVector")
           }
)

setMethod(f = "computeBackwardVector", 
          signature = "HiddenMarkovModel", 
          definition = function(hmm_object)
          {
            observation = getObservationsFromHMM(hmm_object)
            nObservations  = length(observation)
            nStates    = dim(getTransitionMatrix(hmm_object))[1]
            transition_matrix = getTransitionMatrix(hmm_object)
            p <- hmm_object@p
            theta <- getTheta(hmm_object)
            hmm_object <- computeB(hmm_object)
            b0 <- hmm_object@b
            allprobs <- computeAllProbabilities(observation,theta, 
                                                p, b0)
            backward = array(NA,c(nStates,nObservations))
            # Init
            backward[,nObservations] = log(1)
            # Iteration
            for(k in (nObservations-1):1)
            {
              for(state in 1:nStates)
              {
                logsum = -Inf
                for(nextState in 1:nStates)
                {
                  temp   = backward[nextState,k+1] + 
                    log(transition_matrix[state,nextState]*allprobs[state,k+1])
                  if(temp > - Inf)
                  {
                    logsum = temp + log(1 + exp(logsum-temp))
                  }
                }
                backward[state,k] = logsum
              }
            }
            return(backward)
          }
)

