#' @title Compute forward vector for HMM
#' @description Computes the forward vector and loglikelihood for HMM semi parametric model
#' @param hmm - HiddenMarkovModel object
#' @param observations - vector of observationss generated by the above class
#' @return forward vector and loglikelihood

setGeneric(name = "computeForwardVector",
           def = function(hmm_object)
           {
             standardGeneric("computeForwardVector")
           }
)

setMethod(f = "computeForwardVector",
          signature = "HiddenMarkovModel",
          definition = function(hmm_object, observationss)
          {
            nobservationss  = length(observations)
            nStates    = dim(getTransitionMatrix(hmm_object))[1]
            transition_matrix = getTransitionMatrix(hmm_object)
            theta <- getTheta(hmm_object)
            p <- hmm_object@p
            b <- NewtonRaphson(hmm_object)
            allprobs <- rcpp_computeAllProbabilities(observations,theta,
                                                p, b)
            f = array(NA,c(nStates,nobservationss))
            # Init
            f[,1] = log(computeStartingVector(hmm_object) * allprobs[,1])
            # Iteration
            for(k in 2:nobservationss)
            {
              for(state in 1:nStates)
              {
                logsum = -Inf
                for(previousState in 1:nStates)
                {
                  temp   = f[previousState,k-1] + log(transition_matrix[previousState,state])
                  if(temp > - Inf)
                  {
                    logsum = temp + log(1 + exp(logsum - temp ))
                  }
                }
                f[state,k] = log(allprobs[state,k]) + logsum
              }
            }
            return(f)
          }
)

