#' @title Compute forward vector for HMM
#' @description Computes the forward vector and loglikelihood for HMM semi parametric model
#' @param hmm - HiddenMarkovModel object
#' @param observations - vector of observationss generated by the above class
#' @return forward vector and loglikelihood

setGeneric(name = "computeForwardVector",
           def = function(hmm_object, observations)
           {
             standardGeneric("computeForwardVector")
           }
)

setMethod(f = "computeForwardVector",
          signature = "HiddenMarkovModel",
          definition = function(hmm_object, observations)
          {
            transition_matrix <- getTransitionMatrix(hmm_object)
            theta <- getTheta(hmm_object)
            p <- hmm_object@p
            b <- NewtonRaphson(observations,theta,p,500)
            log_forward <- rcpp_forwardVector(observations,transition_matrix,
                                              theta,p,b)
            return(log_forward)
          }
)

