#' @title Compute forward vector for HMM
#' @description Computes the forward vector and loglikelihood for HMM semi parametric model
#' @param hmm - HiddenMarkovModel object
#' @param observation - vector of observations generated by the above class
#' @return forward vector and loglikelihood

setGeneric(name = "computeBackwardVector",
           def = function(hmm_object, observations)
           {
             standardGeneric("computeBackwardVector")
           }
)

setMethod(f = "computeBackwardVector",
          signature = "HiddenMarkovModel",
          definition = function(hmm_object, observations)
          {
            transition_matrix <- getTransitionMatrix(hmm_object)
            theta <- getTheta(hmm_object)
            p <- hmm_object@p
            b <- NewtonRaphson(observations,theta,p,500)
            log_backward <- rcpp_backwardVector(observations,transition_matrix,
                                              theta,p,b)
            return(log_backward)
          }
)

